### ISSUE TITLE
Sneaky trailing comma

### ISSUE THREAD

**Issue by qexat** [jazziiRed/nbs-converter#2]
Hello! I've watched your video, and the project is awesome!

I am currently attempting to add type hints and related stuff, and while I was doing so, I noticed a sneaky trailing comma [in this file](https://github.com/jazziiRed/nbs-converter/blob/main/constants.py#L5).

```py
NAME_DISCS = 0,
```

This makes `NAME_DISCS` a `tuple[int]` instead of an `int` (although I think it probably should be a `bool`), which can lead to unintended behavior/bugs...

Here's what you probably wanted:
```py
NAME_DISCS = 0
```

I made a PR (#3) to fix that.

Have a good day!

**Comment by jazziiRed** [comment]
Good catch, thank you. I'm not sure how that comma got in there

**Comment by jazziiRed** [comment]
PR merged
